{% set name = "pytkdocs" %}
{% set version = "0.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytkdocs-{{ version }}.tar.gz
  sha256: e63ec71dc5e9feabc672f862f04394abd26557c7831c25cb8a60c99af36693b9

build:
  number: 2
  entry_points:
    - pytkdocs = pytkdocs.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<36 and (win64 and py36)]

requirements:
  host:
    - pip
    - python
    - poetry
  run:
    - python
    - astunparse >=1.6.3  # [py<39]
    - dataclasses >=0.7,<0.9  # [py==36]
    - typing_extensions >=3.7.4.3  # [py<38]
    - cached_property >=1.5.2  # [py<38]

test:
  imports:
    - pytkdocs
    - pytkdocs.parsers
  commands:
    - pip check
    - pytkdocs --help
  requires:
    - pip

about:
  home: https://github.com/pawamoy/pytkdocs
  summary: Load Python objects documentation.
  license: ISC
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bandersen23
