{% set name = "pytkdocs" %}
{% set version = "0.16.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytkdocs-{{ version }}.tar.gz
  sha256: 103cdb3f0298c392bc340ae9aa7cd8685b163ae2aec65660dd0018978ddf4fa7

build:
  noarch: python
  number: 0
  entry_points:
    - pytkdocs = pytkdocs.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - pdm-backend
  run:
    - python >={{ python_min }}
    - astunparse >=1.6
    - cached-property >=1.5
    - typing_extensions >=3.7
    - docstring_parser >=0.7
    # - cached_property >=1.5
    # - cached_property >=1.5

test:
  imports:
    - pytkdocs
    - pytkdocs.parsers
    - pytkdocs.loader
    - pytkdocs.objects
    - pytkdocs.cli
  commands:
    - pip check
    - pytest
    - pytkdocs --help
  requires:
    - pip
    - pytest >=6.2
    - pytest-xdist >=2.4
    - django >=3.2
    - marshmallow >=3.13
    - pydantic >=1.8
    - python {{ python_min }}
  source_files:
    - tests

about:
  home: https://github.com/mkdocstrings/pytkdocs
  doc_url: https://mkdocstrings.github.io/pytkdocs/
  summary: Load Python objects documentation.
  license: ISC
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bandersen23
    - cpcloud
